version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./.setup/database/mongodb.entrypoint.js:/docker-entrypoint-initdb.d/mongodb-entrypoint.js
      - nestjs-startkit:/data/db:delegated

    networks:
      - nestjs-startkit
  nestjs-startkit:
    image: node:16-alpine
    container_name: nest
    working_dir: /usr/src/app
    command: ["npm", "run", "start:debug"]
    expose:
      - 3000
      - 9229
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/usr/src/app
    networks:
      - nestjs-startkit
networks:
  nestjs-startkit:
    external: true

volumes:
  nestjs-startkit:
    driver: local
