version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - ./docker/mongodb-entrypoint.js:/docker-entrypoint-initdb.d/mongodb-entrypoint.js
      - jc-customers-mongo:/data/db:delegated

    networks:
      - jcpm-network
  jc-customers:
    image: node:16-alpine
    container_name: jc-customers
    working_dir: /usr/src/app
    command: ["npm", "run", "start:debug"]
    expose:
      - 3000
      - 9229
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/usr/src/app
    networks:
      - jcpm-network
networks:
  jcpm-network:
    external: true

volumes:
  jc-customers-mongo:
    driver: local
